name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  DeterminateCI:
    uses: grahamc/determinate-ci/.github/workflows/workflow.yml@main
    permissions:
      id-token: "write"
      contents: "read"
    with:
      visibility: public
      runner-map: |
        {
          "aarch64-darwin": "macos-latest",
          "x86_64-darwin": "macos-latest",
          "x86_64-linux": "namespace-profile-default",
          "i686-linux": "namespace-profile-default"
        }
